import { useEffect, useReducer, useState } from "react";
import { BrandLogo, BrandMark } from "./components/Brand";
import { initialRuntimeState, runtimeReducer } from "./runtime/reducer";
import { MockTaskRuntimeAdapter } from "./runtime/mockAdapter";
import type { RuntimeEvent, Task } from "./runtime/contracts";

const adapter = new MockTaskRuntimeAdapter();
type ThemeMode = "system" | "light" | "dark";

export function App() {
  const [state, dispatch] = useReducer(runtimeReducer, initialRuntimeState);
  const [prompt, setPrompt] = useState("");
  const [selectedId, setSelectedId] = useState<string>();
  const [theme, setTheme] = useState<ThemeMode>(() => (localStorage.getItem("harness-theme") as ThemeMode) || "system");
  const developer = window.location.pathname.startsWith("/dev");
  const tasks = state.order.map((id) => state.tasks[id]);
  const selected = selectedId ? state.tasks[selectedId] : tasks[0];
  const run = async (value = prompt) => { if (!value.trim()) return; const task = await adapter.createTask({ prompt: value.trim() }); setPrompt(""); setSelectedId(task.id); const unsubscribe = adapter.subscribe(task.id, dispatch); window.setTimeout(unsubscribe, 9000); };
  useEffect(() => { if (!selectedId && tasks[0]) setSelectedId(tasks[0].id); }, [selectedId, tasks]);
  useEffect(() => { document.documentElement.dataset.theme = theme === "system" ? "" : theme; localStorage.setItem("harness-theme", theme); }, [theme]);
  return <div className={`app ${developer ? "developer-mode" : ""}`}><AppShell developer={developer} theme={theme} onThemeChange={setTheme}>{developer ? <DeveloperWorkspace tasks={tasks} selected={selected} onSelect={setSelectedId} /> : <UserWorkspace tasks={tasks} selected={selected} prompt={prompt} setPrompt={setPrompt} onRun={() => run()} onRetry={() => selected && run(selected.prompt)} onCancel={() => selected && adapter.cancelTask(selected.id)} onSelect={setSelectedId} />}</AppShell></div>;
}

function AppShell({ developer, children, theme, onThemeChange }: { developer: boolean; children: React.ReactNode; theme: ThemeMode; onThemeChange: (theme: ThemeMode) => void }) { const nextTheme: ThemeMode = theme === "system" ? "light" : theme === "light" ? "dark" : "system"; const themeLabel = theme === "system" ? "系统" : theme === "light" ? "浅色" : "深色"; return <div className="shell"><aside className="app-rail"><a className="app-logo" href="/app" aria-label="回到工作区"><BrandLogo /></a><div className="rail-group"><a className={!developer ? "rail-link active" : "rail-link"} href="/app"><span>⌂</span><small>任务</small></a><a className={developer ? "rail-link active" : "rail-link"} href="/dev"><span>⌁</span><small>开发</small></a></div><div className="rail-bottom"><button className="rail-link theme-toggle" onClick={() => onThemeChange(nextTheme)} aria-label={`切换主题，当前为${themeLabel}`} title={`主题：${themeLabel}，点击切换`}><span>{theme === "dark" ? "☾" : theme === "light" ? "☀" : "◐"}</span><small>{themeLabel}</small></button><button className="rail-link" aria-label="设置"><span>⚙</span><small>设置</small></button><span className="avatar">A</span></div></aside><div className="shell-body"><header className="app-header"><div className="header-title"><span className="header-kicker">{developer ? "Developer console" : "Workspace"}</span><strong>{developer ? "运行观测" : "任务空间"}</strong></div><div className="header-actions"><BrandLogo compact /><span className="connection"><i />本地连接</span><span className="avatar small-avatar">A</span></div></header>{children}</div></div>; }

function UserWorkspace({ tasks, selected, prompt, setPrompt, onRun, onRetry, onCancel, onSelect }: { tasks: Task[]; selected?: Task; prompt: string; setPrompt: (value: string) => void; onRun: () => void; onRetry: () => void; onCancel: () => void; onSelect: (id: string) => void }) { const running = selected?.status === "queued" || selected?.status === "running"; return <main className="conversation-layout"><aside className="conversation-sidebar"><button className="new-task" onClick={() => onSelect("")}><span>＋</span> 新建任务 <kbd>Ctrl N</kbd></button><button className="search-task"><span>⌕</span> 搜索任务 <kbd>Ctrl K</kbd></button><div className="sidebar-section"><div className="sidebar-label">最近任务</div>{tasks.length ? tasks.map((task) => <button className={`conversation-item ${task.id === selected?.id ? "selected" : ""}`} key={task.id} onClick={() => onSelect(task.id)}><span>{task.prompt}</span><small><i className={task.status} />{task.statusLabel}</small></button>) : <p className="sidebar-empty">还没有任务，开始一次新的对话吧。</p>}</div><div className="sidebar-footer"><span className="workspace-dot" />本地工作区</div></aside><section className="conversation-main">{selected ? <><div className="conversation-scroll"><div className="conversation-heading"><span className="eyebrow">当前任务</span><h1>{selected.prompt}</h1></div><div className="message user-message"><span className="message-avatar">A</span><div><small>你</small><p>{selected.prompt}</p></div></div><div className="message agent-message"><span className="agent-avatar"><BrandMark compact /></span><div><small>Agent <StatusPill task={selected} /></small>{selected.events.length > 1 && <RunSummary task={selected} />}{selected.streamedOutput && <p>{selected.streamedOutput}{running && <span className="typing">▌</span>}</p>}{selected.result && <p>{selected.result}</p>}{selected.error && <div className="user-error">{selected.error.message}</div>}</div></div></div><Composer prompt={prompt} setPrompt={setPrompt} onRun={onRun} disabled={running} /></> : <><div className="welcome"><span className="welcome-mark"><BrandMark /></span><span className="eyebrow">Harness Workbench</span><h1>今天想一起完成什么？</h1><p>描述一个任务，Agent 会在你的工作区里逐步推进。</p><div className="suggestions"><button onClick={() => setPrompt("分析这个项目的结构并给出下一步建议")}>分析项目结构 <span>↗</span></button><button onClick={() => setPrompt("帮我整理当前开发任务")}>整理开发任务 <span>↗</span></button></div></div><Composer prompt={prompt} setPrompt={setPrompt} onRun={onRun} disabled={false} /></>}</section>{selected && <aside className="conversation-meta"><span className="eyebrow">任务信息</span><div className="meta-row"><small>状态</small><StatusPill task={selected} /></div><div className="meta-row"><small>事件</small><strong>{selected.events.length}</strong></div>{running && <button className="stop-button" onClick={onCancel}>停止运行</button>}{selected.status === "failed" && <button className="retry-button" onClick={onRetry}>重新运行</button>}</aside>}</main>; }

function Composer({ prompt, setPrompt, onRun, disabled }: { prompt: string; setPrompt: (value: string) => void; onRun: () => void; disabled: boolean }) { return <div className="composer-wrap"><div className="composer card"><textarea aria-label="任务内容" value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") onRun(); }} placeholder="输入任务，按 Ctrl + Enter 发送" /><div className="composer-tools"><button aria-label="添加文件">＋</button><span>Agent</span><span className="tool-chip">自动</span><span className="composer-spacer" /><small>Ctrl ↵</small><button className="send-button" onClick={onRun} disabled={!prompt.trim() || disabled} aria-label="发送">↑</button></div></div><small className="composer-note">Agent 生成的内容可能需要复核。</small></div>; }
function RunSummary({ task }: { task: Task }) { const active = task.status === "running" || task.status === "queued"; return <div className={`run-summary ${active ? "active" : ""}`}><span className="run-beacon">{active ? "◌" : "✓"}</span><span>{active ? "正在处理任务" : "已完成运行"}</span><small>{task.events.length} 个运行事件</small></div>; }
function DeveloperWorkspace({ tasks, selected, onSelect }: { tasks: Task[]; selected?: Task; onSelect: (id: string) => void }) { const [eventIndex, setEventIndex] = useState(0); const events = selected?.events ?? []; const event = events[eventIndex]; return <main className="developer-main"><div className="dev-title"><div><span className="eyebrow">运行观测</span><h1>关键日志与<em>执行轨迹。</em></h1></div><div className="dev-summary"><strong>{tasks.length}</strong><span>个会话<br />内存中</span></div></div><div className="dev-workbench"><aside className="session-panel card"><div className="panel-title"><span>Sessions</span><b>{tasks.length}</b></div>{tasks.map((task) => <button className={`session-item ${task.id === selected?.id ? "selected" : ""}`} key={task.id} onClick={() => { onSelect(task.id); setEventIndex(0); }}><span>{task.prompt}</span><small>{task.id}</small></button>)}</aside><section className="event-panel card"><div className="panel-title"><span>事件时间线</span><b>{selected?.status ?? "idle"}</b></div>{events.length ? events.map((item, index) => <button className={`event-item ${index === eventIndex ? "selected" : ""}`} key={`${item.type}-${index}`} onClick={() => setEventIndex(index)}><i /><span><strong>{item.type}</strong><small>{eventLabel(item)}</small></span><time>{"timestamp" in item ? new Date(item.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "—"}</time></button>) : <p className="muted">在用户面板创建任务后，这里会显示运行事件。</p>}</section><aside className="event-inspector card"><div className="panel-title"><span>事件详情</span><b>RAW</b></div>{event ? <><div className="inspector-type">{event.type}</div><pre>{JSON.stringify(event, null, 2)}</pre></> : <p className="muted">点击时间线中的事件查看详情。</p>}</aside></div></main>; }
function eventLabel(event: RuntimeEvent) { if ("toolName" in event) return event.toolName; if ("status" in event) return event.status; if ("content" in event) return "stream delta"; return "lifecycle"; }
function StatusPill({ task }: { task: Task }) { return <span className={`status-pill ${task.status}`}><i />{task.statusLabel}</span>; }
